# Generated by Django 4.2.9 on 2024-01-23 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matches',
        ),
        migrations.DeleteModel(
            name='PongMatch',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
