# Generated by Django 4.2.9 on 2024-02-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='channels_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='main_channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
