# Generated by Django 4.2.9 on 2024-02-10 21:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=users.models.random_default_image, upload_to='profile_pics'),
        ),
    ]
