CREATE DATABASE :POSTGRES_DB;
\c :POSTGRES_DB	-- Activate database

CREATE USER :POSTGRES_USER WITH ENCRYPTED PASSWORD :'POSTGRES_PASSWORD';
ALTER USER :POSTGRES_USER CREATEDB;

GRANT ALL PRIVILEGES ON DATABASE :POSTGRES_DB TO :POSTGRES_USER;
